### ISSUE TITLE
Frosted Glass

### ISSUE THREAD

**Issue by naveeramesh** [Dezenix/native-frontend-flutter#10]
## Create a frosted glass effect
Follow the guidelines and code of conduct
[Frosted glass folder](https://github.com/Dezenix/native-frontend-flutter/tree/main/Frosted%20glass/frosted_glass) check the readme and do necessary changes ,and follow the code structure.

**Comment by suyogkokaje** [comment]
Hello I would like to work on this issue. Could you please assign this issue to me?

**Comment by naveeramesh** [comment]
> Hello I would like to work on this issue. Could you please assign this issue to me?

Your from Swoc right?

**Comment by suyogkokaje** [comment]
Yes. I am SWoC participant.

**Comment by naveeramesh** [comment]
@suyogkokaje  yeah, you can start working.

**Comment by msramesh2k1** [comment]
Hey @naveeramesh in the whole project frosted glass is showing error b'coz of null safety .

**Comment by naveeramesh** [comment]
> Hey @naveeramesh in the whole project frosted glass is showing error b'coz of null safety .

Okay leme check

**Comment by suyogkokaje** [comment]
Actually I am not much aware about null safety 😅. Sorry 😓.

**Comment by naveeramesh** [comment]
> Actually I am not much aware about null safety 😅. Sorry 😓.

Okay but try to learn null safety for further contribution.

**Comment by suyogkokaje** [comment]
Yeah I will try to learn.
