### ISSUE TITLE
Crypto Currency Tracking App

### ISSUE THREAD

**Issue by mdnazisharman2803** [Dezenix/native-frontend-flutter#109]
### Description

Idea is to make UI of  crypto Currency Tracking app.
It'll include

- Home Screen
- Tracking Graph of currency

### Additional information

As a participant of GSSOC '22, I myself would like to work on this issue.

**Comment by mdnazisharman2803** [comment]
@Jaideep25-tech  @naveeramesh  kindly assign me the issue and add GSSoC tag thank you

**Comment by naveeramesh** [comment]
Complete the previous issue and you can move on to this I'll create issues today so don't create new one iam closing this issue.
