### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by naveeramesh** [Dezenix/native-frontend-flutter#12]
Create a Landing Page for a furniture shop.
Follow the Guidelines and code of conduct.
Check the [Landing Page](https://github.com/Dezenix/native-frontend-flutter/tree/main/LandingPage/furniture_landingpg) once.

**Comment by Sumit4482** [comment]
I can try to do this task,can you assign it me ?

**Comment by naveeramesh** [comment]
@Sumit4482 mention from which org your WOC or swoc

**Comment by Sumit4482** [comment]
I doesn't belong to any of this organization.

**Comment by naveeramesh** [comment]
@Sumit4482 Then sry this open source comes under these both so once those completed I'll assign you mean while join this server https://discord.gg/F3TtF5AHKz

**Comment by Sumit4482** [comment]
Thank you !
I have joined the discord server.

**Comment by naveeramesh** [comment]
@Sumit4482 you can work on this issue.

**Comment by Sumit4482** [comment]
@naveeramesh ok thanks,
I will complete it in few days
