### ISSUE TITLE
Chat List

### ISSUE THREAD

**Issue by naveeramesh** [Dezenix/native-frontend-flutter#14]
Create a Chatlist similar to instagram.
Follow the [Guidelines](https://github.com/Dezenix/native-frontend-flutter/blob/main/Guidelines.md) and code of conduct.
Check the [Chatlist folder](https://github.com/Dezenix/native-frontend-flutter/blob/main/chat/chat_list/README.md) once.

**Comment by Aneesh015** [comment]
I would like to take up this issue,as part of SWoC.

**Comment by Sumit4482** [comment]
@naveeramesh  
I would like to work on this issue, can you please assign it to me?

**Comment by nrd26** [comment]
Hi,
Due to my current commitments, I will not be able to work on this issue. I'm very sorry for any inconvenience this has caused.
