### ISSUE TITLE
Chat Screen

### ISSUE THREAD

**Issue by naveeramesh** [Dezenix/native-frontend-flutter#16]
Create a Chat Screen 
Follow the [Guidelines](https://github.com/Dezenix/native-frontend-flutter/blob/main/Guidelines.md) and code of conduct.
Check the [Chat Screen](https://github.com/Dezenix/native-frontend-flutter/tree/main/chat/chat_screen) once.

**Comment by sanjanarp** [comment]
Is it just the UI that has to be implemented, without any backend? Could you please brief out about what all has to be implemented on the screen?

**Comment by naveeramesh** [comment]
@sanjanarp just the UI part to be done 
1. Implement background image
2. The messages can be hard coded 
3. You can also implement your own creativity for styling but what was defined in the readme is mandatory.

**Comment by sanjanarp** [comment]
Oh okay , I'm up for this issue

**Comment by kritigupta45** [comment]
I would like to work on this issue, can you please assign it to me? @naveeramesh
