### ISSUE TITLE
Custom bottom bar

### ISSUE THREAD

**Issue by naveeramesh** [Dezenix/native-frontend-flutter#18]
Create a custom bottom navigation bar without using packages
Refer various UI designs from [Dribbble](https://dribbble.com/search/bottom%20navigation%20bar)
Make a smooth working custom bottom bar
Follow the [Guidelines](https://github.com/Dezenix/native-frontend-flutter/blob/main/Guidelines.md) and code of conduct when your pushing changes.

Folder structure:
Custom Widgets\custom_bottombar01\

**Comment by SharviE29** [comment]
Hello , I'll like to work on this issue. Could you please assign it to me?
Thanks in advance.

**Comment by naveeramesh** [comment]
> Hello , I'll like to work on this issue. Could you please assign it to me? Thanks in advance.

Mention the organisation too.

**Comment by SharviE29** [comment]
> > Hello , I'll like to work on this issue. Could you please assign it to me? Thanks in advance.
> 
> Mention the organisation too.

I'm a SWoC participant. Thank you

**Comment by SharviE29** [comment]
I'll have to create a new folder for adding this file right?

**Comment by naveeramesh** [comment]
> I'll have to create a new folder for adding this file right?

Yeah!
