### ISSUE TITLE
Create a slide bar

### ISSUE THREAD

**Issue by naveeramesh** [Dezenix/native-frontend-flutter#19]
Create a slide bar with Shimmer effect
Refer some existing design and bring some innovative Slide bar
Follow the [Guidelines](https://github.com/Dezenix/native-frontend-flutter/blob/main/Guidelines.md) and code of conduct when your pushing changes.

Folder structure:
Shimmer\shimmer_slidebar01\

**Comment by naveeramesh** [comment]
Yes you can @SamridhiSethi13

**Comment by SamridhiSethi13** [comment]
Do I have to follow any particular theme _(for eg. WhatsApp follows a theme of white and green)_ or I can create a theme of my own?

**Comment by naveeramesh** [comment]
Do on your own theme

**Comment by SamridhiSethi13** [comment]
@naveeramesh can you please review my PR?
