### ISSUE TITLE
Website login Screen

### ISSUE THREAD

**Issue by naveeramesh** [Dezenix/native-frontend-flutter#21]
As Flutter supports Website
Create a responsive Web Login Screen 
Refer various UI designs from [Dribbble](https://dribbble.com/search/login%20website)
Follow the [Guidelines](https://github.com/Dezenix/native-frontend-flutter/blob/main/Guidelines.md) and code of conduct when your pushing changes.

Folder structure:
Login_Screens\login_web01\

**Comment by msramesh2k1** [comment]
@naveeramesh I have finished my two issues , now can you plz assign this work

**Comment by naveeramesh** [comment]
@msramesh2k1 go ahead
