### ISSUE TITLE
Neumorphic effect

### ISSUE THREAD

**Issue by naveeramesh** [Dezenix/native-frontend-flutter#24]
Create a music player home screen with Neumorphic effect 
Refer various UI designs from [Dribbble](https://dribbble.com/)
Follow the [Guidelines](https://github.com/Dezenix/native-frontend-flutter/blob/main/Guidelines.md) and code of conduct when your pushing changes.

Folder structure:
Neumorphism\musicplayer\

**Comment by suyogkokaje** [comment]
Hello @naveeramesh I would like to work on this issue. Could you please assign this issue to me? I am SWoC participant.

**Comment by suyogkokaje** [comment]
Okay. I will keep that in mind. Thanks for telling 😄.
