### ISSUE TITLE
Shimmer listview

### ISSUE THREAD

**Issue by naveeramesh** [Dezenix/native-frontend-flutter#27]
Create a List View with Shimmer effect
Refer some existing design and bring some innovative Slide bar
Follow the [Guidelines](https://github.com/Dezenix/native-frontend-flutter/blob/main/Guidelines.md) and code of conduct when your pushing changes.

Folder structure:
Shimmer\shimmer_lisview_01\

**Comment by msramesh2k1** [comment]
can you assign me this @naveeramesh

**Comment by naveeramesh** [comment]
@msramesh2k1 Once you pr got accepted i'll assign you

**Comment by msramesh2k1** [comment]
then can you plz accept asap
