### ISSUE TITLE
Null safety

### ISSUE THREAD

**Issue by naveeramesh** [Dezenix/native-frontend-flutter#29]
Solve the null safety issue for [Frosted glass](https://github.com/Dezenix/native-frontend-flutter/tree/main/Frosted%20glass/frosted_glass)
Follow the [Guidelined](https://github.com/Dezenix/native-frontend-flutter/blob/main/Guidelines.md) while your doing changes.

File located :
Frosted glass/frosted_glass

**Comment by msramesh2k1** [comment]
can I work on this issue
