### ISSUE TITLE
verification page

### ISSUE THREAD

**Issue by Jaideep25-tech** [Dezenix/native-frontend-flutter#33]
### Description

Create a verification page
Follow the [Guidelines](https://github.com/Dezenix/native-frontend-flutter/blob/main/Guidelines.md) and code of conduct when your pushing changes.

Folder structure:
Verificarion pages\verification_page_01\

**Comment by msramesh2k1** [comment]
Hey @Jaideep25-tech Can I work on this issue

**Comment by Jaideep25-tech** [comment]
yeah bro you can but remember the folder structure, guidelines and commit message!

**Comment by msramesh2k1** [comment]
Hey @Jaideep25-tech verification page is like OTP verification page ??

**Comment by Jaideep25-tech** [comment]
yeah bro
