### ISSUE TITLE
Hero animation

### ISSUE THREAD

**Issue by naveeramesh** [Dezenix/native-frontend-flutter#35]
Create two screens 
Screen 1 : List of products
Screen 2 : Product Description
Implement Hero animation while navigating from Screen 1 to Screen 2
Follow the [Guidelines](https://github.com/Dezenix/native-frontend-flutter/blob/main/Guidelines.md) and code of conduct when your pushing changes.

Folder structure:
Animation\hero\

**Comment by SharviE29** [comment]
I'll like to work on this issue. Could you please assign it to me? I'm a SWoC participant.
