### ISSUE TITLE
Theme

### ISSUE THREAD

**Issue by naveeramesh** [Dezenix/native-frontend-flutter#36]
Work on 
1. System default theme
2. Light mode
3. Dark mode
Follow the [Guidelines](https://github.com/Dezenix/native-frontend-flutter/blob/main/Guidelines.md) and code of conduct when your pushing changes.

Folder structure:
Theme\

**Comment by msramesh2k1** [comment]
can you assign this for me
@naveeramesh

**Comment by Pavan49719** [comment]
I would like to work on this issue. Could you please assign this to me?
