### ISSUE TITLE
Custom Dialog

### ISSUE THREAD

**Issue by naveeramesh** [Dezenix/native-frontend-flutter#37]
### What would you like to share?

Create a custom dialog box
Follow the [Guidelines](https://github.com/Dezenix/native-frontend-flutter/blob/main/Guidelines.md) and code of conduct when your pushing changes.

Folder structure:
Custom Widgest\custom_dialog

### Additional information

![image](https://user-images.githubusercontent.com/54928117/146375403-faa9a625-e99b-47d7-a690-ebc00eb24eb0.png)

**Comment by msramesh2k1** [comment]
can I work on this issue
