### ISSUE TITLE
Social Media 

### ISSUE THREAD

**Issue by naveeramesh** [Dezenix/native-frontend-flutter#38]
Create a Social Media Handle home page
Take reference of Insta, Facebook but don't create the exact same
Follow the [Guidelines](https://github.com/Dezenix/native-frontend-flutter/blob/main/Guidelines.md) and code of conduct when your pushing changes.

Folder structure:
Landing Page\socialmedia_home

**Comment by Pranav108** [comment]
I would love to give this a try, can I take it?

**Comment by naveeramesh** [comment]
Mention your organization?

**Comment by mdnazisharman2803** [comment]
assign to me

**Comment by mdnazisharman2803** [comment]
Can't add Gssoc label?

**Comment by mdnazisharman2803** [comment]
@naveeramesh , @Jaideep25-tech kindly close this issue as it has been completed
