### ISSUE TITLE
Option selection page

### ISSUE THREAD

**Issue by Jaideep25-tech** [Dezenix/native-frontend-flutter#39]
### Description

Create an option selection page for design tools
Follow the Guidelines and code of conduct when your pushing changes.

**Comment by txxthxx** [comment]
I'd like to work on this issue.

**Comment by Jaideep25-tech** [comment]
sure you can but remember the folder structure, guidelines, and commit message!

**Comment by naveeramesh** [comment]
@txxthxx have you completed?
