### ISSUE TITLE
weather app ui

### ISSUE THREAD

**Issue by Jaideep25-tech** [Dezenix/native-frontend-flutter#46]
### Description

Create the weather app UI as given below.
Follow the Guidelines and code of conduct when you push changes.

### Screenshots

![image](https://user-images.githubusercontent.com/79747022/147131276-1e9b0b35-5860-44b9-8a85-474ab22830df.png)

**Comment by thenose-samuel** [comment]
I would like to take this up

**Comment by Jaideep25-tech** [comment]
sure

**Comment by garvitraj** [comment]
@Jaideep25-tech pls sahre the figma file with the participant in the issue so that its easy for them to do the design and styling

**Comment by Jaideep25-tech** [comment]
> @Jaideep25-tech pls sahre the figma file with the participant in the issue so that its easy for them to do the design and styling

Already shared
