### ISSUE TITLE
Welcome Screen

### ISSUE THREAD

**Issue by Jaideep25-tech** [Dezenix/native-frontend-flutter#47]
### Description

Create the welcome screen as given below
Follow the Guidelines and code of conduct when you push changes.

### Screenshots

![image](https://user-images.githubusercontent.com/79747022/147131655-1f4c489d-bff8-4bb6-967d-3bec05fe11e4.png)

**Comment by divyasreedev** [comment]
I would like to take this up.

**Comment by Jaideep25-tech** [comment]
sure

**Comment by garvitraj** [comment]
@Jaideep25-tech pls sahre the figma file with the participant in the issue so that its easy for them to do the design and styling
