### ISSUE TITLE
Onboarding screen with sign in and sign up

### ISSUE THREAD

**Issue by Jaideep25-tech** [Dezenix/native-frontend-flutter#48]
### Description

create the UI screen as given below
Follow the Guidelines and code of conduct when you push changes.

### Screenshots

![image](https://user-images.githubusercontent.com/79747022/147131799-7bb8ed2a-bfeb-4eb1-872a-70191bcae54b.png)

**Comment by Pranav108** [comment]
I would like to work on it?

**Comment by Jaideep25-tech** [comment]
sure

**Comment by nithiink** [comment]
I would also like to work on it?

**Comment by Pranav108** [comment]
@nithiink I'm already working on it.

**Comment by nithiink** [comment]
> @nithiink I'm already working on it.

Oops sorry

**Comment by garvitraj** [comment]
@Jaideep25-tech pls share the Figma file with the participant in the issue so that its easy for them to do the design and styling
