### ISSUE TITLE
Login Screen 

### ISSUE THREAD

**Issue by naveeramesh** [Dezenix/native-frontend-flutter#5]
Create a simple Login Screen with minimalistic components.
Follow the Guidelines and code of conduct.
Check the [Login Folder](https://github.com/Dezenix/native-frontend-flutter/tree/main/Login_Screens/Login01) once.

**Comment by sanjanarp** [comment]
I would like to work on this issue under SWOC 2.0

**Comment by sanjanarp** [comment]
Can I add the Dezenix logo and some animation to the login screen?

**Comment by naveeramesh** [comment]
> @naveeramesh Can I add the Dezenix logo and some animation to the login screen?

Go-ahead!
