### ISSUE TITLE
Music Player App Design

### ISSUE THREAD

**Issue by naveeramesh** [Dezenix/native-frontend-flutter#50]
We gonna develop a complete UI for Music Player App - Spotify Clone
Screens to be develop:
1. SplashScreen
2. Signup Screen[completed]
3. Signin Screen[completed]
4. HomeScreen
5. Settings Screen
6. Music List Screen
7. Music Play screen

Follow the [Guidelines](https://github.com/Dezenix/native-frontend-flutter/blob/main/Guidelines.md) and code of conduct when your pushing changes.

Do the project in Music Player folder which is already created.

**Comment by msramesh2k1** [comment]
I would like to work on settings screen

**Comment by naveeramesh** [comment]
> I would like to work on settings screen

Yeah, sure I'll create a separate issue for the settings screen you can work on it.

**Comment by msramesh2k1** [comment]
@naveeramesh can I start b'coz no one getting assigned , if you tell me the setting screen sample I can do that

**Comment by naveeramesh** [comment]
> @naveeramesh can I start b'coz no one getting assigned , if you tell me the setting screen sample I can do that

Okay , take an example of Spotify app settings screen and start your work.

**Comment by msramesh2k1** [comment]
Cool

**Comment by SharviE29** [comment]
I had a doubt, do we have to create an exact replica of the UI of Spotify, or we are supposed to make some changes to it?

**Comment by naveeramesh** [comment]
> I had a doubt, do we have to create an exact replica of the UI of Spotify, or we are supposed to make some changes to it?

Follow same colour combination,
But you can refer the screen design rather than making exact clone.

**Comment by SharviE29** [comment]
Ok...I would like to work on the sign-in and the sign-up screen then

**Comment by naveeramesh** [comment]
Sure you can , I'll create seperate issue for you.

**Comment by SharviE29** [comment]
Thank you! I forgot to mention that I'm a SWoC participant

**Comment by Pavan49719** [comment]
I would like to work on Splash Screen.

**Comment by naveeramesh** [comment]
I'll create seperate issue for you.

**Comment by StarTrooper08** [comment]
Anyone working on HomeScreen or Music List screen?
If not can work on those!?

**Comment by naveeramesh** [comment]
No,which screen you need to work home / music list , mention your org.

**Comment by StarTrooper08** [comment]
Org!?

I'm SWOC participant forgot to mention that😅

**Comment by naveeramesh** [comment]
> Org!?
> 
> I'm SWOC participant forgot to mention that😅

Are you willing to design both screens Home and Music or mention any one?

**Comment by StarTrooper08** [comment]
Anyone

**Comment by naveeramesh** [comment]
Created a issue for you @StarTrooper08

**Comment by mdnazisharman2803** [comment]
@naveeramesh  mam can you assign Me this issue and fix label.. I'll be working on the rest of the screen in music player app
