### ISSUE TITLE
Shopping app UI

### ISSUE THREAD

**Issue by Jaideep25-tech** [Dezenix/native-frontend-flutter#53]
### Description

We gonna develop a complete UI for shopping app
Screens to be developed:

SplashScreen
Signup Screen
HomeScreen
Item list
Cart Screen
Follow the Guidelines and code of conduct when your pushing changes.

Do the project in shopping app folder create a folder named vegetable shopping app

### Screenshots

![image](https://user-images.githubusercontent.com/79747022/147590429-a4bcf46b-dba6-42fe-afa9-13594b5a9e23.png)

**Comment by thenose-samuel** [comment]
I wanna take this up

**Comment by Jaideep25-tech** [comment]
sure bro. but remember the commit message and folder structure while pushing the code
