### ISSUE TITLE
Settings screen

### ISSUE THREAD

**Issue by naveeramesh** [Dezenix/native-frontend-flutter#55]
Under music player app design 
1. Settings screen

**Comment by msramesh2k1** [comment]
I will do

**Comment by Subhajitongit** [comment]
Hey, could you please assign me the task?

**Comment by mdnazisharman2803** [comment]
@naveeramesh  this issue is of [Neumorphism](https://github.com/Dezenix/native-frontend-flutter/tree/main/Neumorphism) music player app and there is not any settings screen, assign me . i will do it

**Comment by mdnazisharman2803** [comment]
@naveeramesh  mam close this pr as it's done
