### ISSUE TITLE
Shopping app UI

### ISSUE THREAD

**Issue by Jaideep25-tech** [Dezenix/native-frontend-flutter#58]
### Description

We gonna develop a complete UI for shopping app of music accessories
Screens to be developed:

Signup Screen
Sign in Screen
HomeScreen
Item list
search screen
Follow the Guidelines and code of conduct when your pushing changes.

Do the project in shopping app folder create a folder named vegetable shopping app

### Screenshots

![image](https://user-images.githubusercontent.com/79747022/147780616-4f96b000-d876-4afd-a57d-14413ecda9e0.png)

**Comment by Pranav108** [comment]
I would like to work on it.

**Comment by Jaideep25-tech** [comment]
Sure bro
