### ISSUE TITLE
Register Screen

### ISSUE THREAD

**Issue by naveeramesh** [Dezenix/native-frontend-flutter#6]
Follow the Guidelines and code of conduct.
Check [Register Screen Folder](https://github.com/Dezenix/native-frontend-flutter/tree/main/RegisterScreen/register_01) readme follow the steps for redesigning the register screen, follow to code structure.

**Comment by sanjanarp** [comment]
I would like to work on this issue under SWOC 2.0

**Comment by Kajal13081** [comment]
@naveeramesh I would like to work on this issue.

**Comment by sanjanarp** [comment]
Could I work on this issue now?

**Comment by naveeramesh** [comment]
> Could I work on this issue now?

Will inform you shortly.

**Comment by sanjanarp** [comment]
@naveeramesh okay

**Comment by naveeramesh** [comment]
@sanjanarp contribute to issue which has swoc label

**Comment by msramesh2k1** [comment]
can I work on this issue
