### ISSUE TITLE
Splash Screen - Music Player app

### ISSUE THREAD

**Issue by naveeramesh** [Dezenix/native-frontend-flutter#63]
Under music player app design 
1. Splash screen

**Comment by Pavan49719** [comment]
Could I work on this?

**Comment by msramesh2k1** [comment]
hey @Pavan49719 can plz tell me whether you got any error while running music_player app

**Comment by Pavan49719** [comment]
> 

For me it's running on chrome as a web app, but not on android.

**Comment by Pavan49719** [comment]
> hey @Pavan49719 can plz tell me whether you got any error while running music_player app

@msramesh2k1 Are you getting the same error
![image](https://user-images.githubusercontent.com/90468365/148651872-8ede47cc-0259-408e-9fab-c91f373df63e.png)

**Comment by msramesh2k1** [comment]
Yes , it is due to missing of Android manifest file . @naveeramesh will do by tomorrow

**Comment by Pavan49719** [comment]
> Yes , it is due to missing of Android manifest file . @naveeramesh will do by tomorrow

Yeah got it, Thanks

**Comment by naveeramesh** [comment]
@Pavan49719 rectified

**Comment by naveeramesh** [comment]
@Pavan49719 clone again now and start work
