### ISSUE TITLE
Home screen - Music Player app

### ISSUE THREAD

**Issue by naveeramesh** [Dezenix/native-frontend-flutter#64]
Under music player app design

1.Home Screen

**Comment by StarTrooper08** [comment]
Can you please assign me this issue.

**Comment by naveeramesh** [comment]
@StarTrooper08 clone again and start working.

**Comment by StarTrooper08** [comment]
clone again!
Why?

**Comment by naveeramesh** [comment]
It shows error while you run the application so now it has been rectified try to clone once to again to avoid the error or go with git pull.

**Comment by StarTrooper08** [comment]
Ok👍. I have pulled the latest updates from the main repository.

**Comment by mdnazisharman2803** [comment]
@naveeramesh  can i work on this issue as well? Will u please fix label and I'll do this if you assign me
