### ISSUE TITLE
Diet app

### ISSUE THREAD

**Issue by naveeramesh** [Dezenix/native-frontend-flutter#71]
### Description

Create a 
login screen 
register screen
Home screen
Settings screen

**Comment by SamridhiSethi13** [comment]
I am a GSSOC'22 participant and would love to work on this issue.

**Comment by naveeramesh** [comment]
You would like to work on which screen

**Comment by chinmayilondhe** [comment]
Hi @naveeramesh I am a GSSOC'22 contributer. Can I work on Login screen?

**Comment by naveeramesh** [comment]
> 

Yes you can carry on the work

**Comment by SamridhiSethi13** [comment]
I can work on home screen

**Comment by akshata1224** [comment]
can I work on register and settings screen?

**Comment by naveeramesh** [comment]
> I can work on home screen

Yeah you can

**Comment by naveeramesh** [comment]
> Hii @naveeramesh, I'm a GSSOC'22 contributor can I work on the register and settings screen?

Yeah you can

**Comment by ayush-1601** [comment]
Hi @naveeramesh, I am a GSSOC'22 contributor and a beginner in open source. Can I work on Login screen?

**Comment by naveeramesh** [comment]
@ayush-1601 yeah you can

**Comment by rahulm-28** [comment]
Hi @naveeramesh, I am a GSSOC'22 contributor. Can I work on Register Screen and Login screen?

**Comment by naveeramesh** [comment]
> Hi @naveeramesh, I am a GSSOC'22 contributor. Can I work on Register Screen and Login screen?

Yeah you can

**Comment by mdnazisharman2803** [comment]
@naveeramesh  please assign me this issue

**Comment by mdnazisharman2803** [comment]
@naveeramesh , I guess it'll be a better idea to have a user profile screen in this app too? Can you add description for it? Or profile screen is not needed??
