### ISSUE TITLE
Podcast app

### ISSUE THREAD

**Issue by naveeramesh** [Dezenix/native-frontend-flutter#77]
### Description

Design a simple UI for HomeScreen of PodCast
Follow the guidelines and code of conduct
While giving the PR make sure you define the issue name
While commenting on the issue mention your a GSSOC participant

**Comment by dasgupta002** [comment]
@naveeramesh I'm looking to work on this one, can you assign me?

**Comment by naveeramesh** [comment]
@Jaideep25-tech can merge
