### ISSUE TITLE
Exercise app

### ISSUE THREAD

**Issue by naveeramesh** [Dezenix/native-frontend-flutter#78]
### Description

Design a entire app UI for Exercise Application
1. Signin Screen
2. Signup screen
3. Interest selection
4. Home Screen
5. Settings Screen
6. Account Screen
7. Displaying what exercise should be done 

Refer healthifyme app for a demo but don't design the same
Each participant can take one screen to design if you need to work on this comment which screen you have to work
Follow the guidelines and code of conduct
While giving the PR make sure you define the issue name
While commenting on the issue mention your a GSSOC participant

**Comment by mdnazisharman2803** [comment]
@naveeramesh  please assign me sign up and sign in screen, I'll make 2 pr for each of them, 
I'm GSSOC 22 participant, 
Please fix label, it should be
GSSoC22 and Level2
I'll be waiting it to get assigned. 

And in which folder I've to do changes let me know, if you assign me fast mam, probably I'll be designing whole app

**Comment by naveeramesh** [comment]
> @naveeramesh please assign me sign up and sign in screen, I'll make 2 pr for each of them, I'm GSSOC 22 participant, Please fix label, it should be GSSoC22 and Level2 I'll be waiting it to get assigned.
> 
> And in which folder I've to do changes let me know, if you assign me fast mam, probably I'll be designing whole app

Create a seperate folder and start working

**Comment by mdnazisharman2803** [comment]
Okk mam

**Comment by mdnazisharman2803** [comment]
Mam we have to code in flutter to design ui Or just only design using figma?

**Comment by naveeramesh** [comment]
Code in flutter

**Comment by mdnazisharman2803** [comment]
@naveeramesh  can you tell me what should be there in intrest selection screen
