### ISSUE TITLE
Splash Screen

### ISSUE THREAD

**Issue by naveeramesh** [Dezenix/native-frontend-flutter#8]
## Create an Splash  Screen
Follow the guidelines and code of conduct
[Splash Screen](https://github.com/Dezenix/native-frontend-flutter/tree/main/SplashScreen/spalsh_video) check the readme file and recreate the design in flutter and follow the code structure.

**Comment by msramesh2k1** [comment]
I would like to work on this issue

**Comment by msramesh2k1** [comment]
I am trying to make video kind of splash and onboarding screen
