### ISSUE TITLE
UI of a Payment Tracker app

### ISSUE THREAD

**Issue by dasgupta002** [Dezenix/native-frontend-flutter#85]
### Description

UI of a payments tracker app having onboarding screen, home screen, smooth navigation and cool charts to graphically project usage data.  

### Screenshots

![UI](https://user-images.githubusercontent.com/62376775/166289870-ae622f58-8b6a-4e09-a0a3-a7123fef57a8.png)

### Additional information

As GSSOC '22 contributor, I myself want to work on this issue. Hoping to get assigned!

**Comment by naveeramesh** [comment]
Have you coded this or yet to be coded?

**Comment by dasgupta002** [comment]
Completed couple of days back, was waiting to get assigned :)

**Comment by dasgupta002** [comment]
@naveeramesh check!
