### ISSUE TITLE
Hidden Drawer bar

### ISSUE THREAD

**Issue by naveeramesh** [Dezenix/native-frontend-flutter#9]
## Hidden Drawer bar
Follow guidelines and code of conduct
[Hidden Drawer bar](https://github.com/Dezenix/native-frontend-flutter/tree/main/Hidden_Darwerbar/drawerbar_01) check the readme file and recreate the design.

**Comment by sanjanarp** [comment]
I would like to work on this issue under SWOC 2.0

**Comment by naveeramesh** [comment]
> I would like to work on this issue under SWOC 2.0

@sanjanarp after completion of one issue you can comment on next one .Happy contribution.

**Comment by Pavan49719** [comment]
Could I please contribute to this issue?
